build: add dependency for Android-DirectoryChooser
when I launch the chooser, I met this error

    E/AndroidRuntime(26862): java.lang.NoClassDefFoundError: com.gu.option.Option
    E/AndroidRuntime(26862):        at net.rdrei.android.dirchooser.DirectoryChooserFragment.<init>(DirectoryChooserFragment.java:60)
    E/AndroidRuntime(26862):        at net.rdrei.android.dirchooser.DirectoryChooserFragment.newInstance(DirectoryChooserFragment.java:90)
    E/AndroidRuntime(26862):        at net.rdrei.android.dirchooser.DirectoryChooserActivity.onCreate(DirectoryChooserActivity.java:38)
    E/AndroidRuntime(26862):        at android.app.Activity.performCreate(Activity.java:5231)

it might be caused by this commit
https://github.com/passy/Android-DirectoryChooser/commit/0a7cd107

just add some dependency like what they did